const DUMMY_TIMERS = [
  {
    id: 0,
    name: 'timer_0',
    list: '',
    listPosition: false,
    tags: [],
    isRunning: false,
    start: 0,
    stop: 0,
    elapsed: 0,
    completed: false,
  },{
    id: 1,
    name: 'timer_1',
    list: '',
    listPosition: false,
    tags: [],
    isRunning: false,
    start: 0,
    stop: 0,
    elapsed: 0,
    completed: false,
  },{
    id: 2,
    name: 'timer_2',
    list: '',
    listPosition: false,
    tags: [],
    isRunning: false,
    start: 0,
    stop: 0,
    elapsed: 0,
    completed: false,
  },{
    id: 3,
    name: 'timer_3',
    list: '',
    listPosition: false,
    tags: [],
    isRunning: false,
    start: 0,
    stop: 0,
    elapsed: 0,
    completed: false,
  },{
    id: 4,
    name: 'timer_4',
    list: '',
    listPosition: false,
    tags: [],
    isRunning: false,
    start: 0,
    stop: 0,
    elapsed: 0,
    completed: false,
  },
  // {
  //   id: 5,
  //   name: 'timer_5',
  //   list: '',
  //   listPosition: false,
  //   tags: [],
  //   isRunning: false,
  //   start: 0,
  //   stop: 0,
  //   elapsed: 0,
  //   completed: false,
  // },{
  //   id: 6,
  //   name: 'timer_6',
  //   list: '',
  //   listPosition: false,
  //   tags: [],
  //   isRunning: false,
  //   start: 0,
  //   stop: 0,
  //   elapsed: 0,
  //   completed: false,
  // },{
  //   id: 7,
  //   name: 'timer_7',
  //   list: '',
  //   listPosition: false,
  //   tags: [],
  //   isRunning: false,
  //   start: 0,
  //   stop: 0,
  //   elapsed: 0,
  //   completed: false,
  // },{
  //   id: 8,
  //   name: 'timer_8',
  //   list: '',
  //   listPosition: false,
  //   tags: [],
  //   isRunning: false,
  //   start: 0,
  //   stop: 0,
  //   elapsed: 0,
  //   completed: false,
  // },{
  //   id: 9,
  //   name: 'timer_9',
  //   list: '',
  //   listPosition: false,
  //   tags: [],
  //   isRunning: false,
  //   start: 0,
  //   stop: 0,
  //   elapsed: 0,
  //   completed: false,
  // },
];

const DUMMY_LISTS = [
  {
    label: 'first',
    value: '0',
  },
  {
    label: 'second',
    value: '1',
  },
  {
    label: 'third',
    value: '2',
  },
  {
    label: 'fourth',
    value: '3',
  },{
    label: 'fifth',
    value: '4',
  },
];

const DUMMY_TAGS = [
  {
    label: 'tag 1',
    value: '0',
  },
  {
    label: 'tag 2',
    value: '1',
  },
  {
    label: 'tag 3',
    value: '2',
  },
  {
    label: 'tag 4',
    value: '3',
  },
  {
    label: 'tag 5',
    value: '4',
  },
];

export {
  DUMMY_TIMERS,
  DUMMY_LISTS,
  DUMMY_TAGS,
}